export {default as Cabecera} from "./Cabecera"
export {default as BotonPrincipal} from "./BotonPrin"
export {default as Ttable} from "./Ttable"
export {default as Accordion} from "./Accordion"
export {default as Buttons} from "./Buttons"